AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - group::dream_realise
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Dream_realiseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: group.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies:
          - AWSLambdaBasicExecutionRole
          - DynamoDBCrudPolicy:
              TableName: "*"
      Timeout: 200
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Dream_realiseApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: Dream_realiseApi
