package group.dto.event;

public record EventDtoWithoutCategoryId(String id,
                                        String organizerType,
                                        String organizerName,
                                        String organizerEmail,
                                        String phone,
                                        String link,
                                        String organizerPhoto,
                                        String title,
                                        String opportunityType,
                                        String assistanceType,
                                        Double target,
                                        String region,
                                        String address,
                                        String startingDate,
                                        String startHour,
                                        String startMinute,
                                        String endingDate,
                                        String endHour,
                                        String endMinute,
                                        String startPeriod,
                                        String endPeriod,
                                        String timeDemands,
                                        String skills,
                                        String coverImage,
                                        String description,
                                        String descriptionLink,
                                        String document,
                                        Double currentProgress) {
}
